import { useEffect, useMemo, useState } from 'react';
import { editor, useEditor } from './store';
import { uid } from './model';
import { compareRuns, directorMoves, isRunStale, newRule, ruleRegistry, type Condition, type DirectorMove, type RuleInstance, type TraceStatus } from './audienceEngine';
import { configureEngine, engineConfig, engineInput, replaySimulation, runSimulation, saveSimulationBaseline } from './audienceSimulation';
const statusLabel: Record<TraceStatus,string>={applied:'已套用',disabled:'已停用',inapplicable:'條件不成立',unknown:'輸入未知',unregistered:'規則未註冊',conflict:'衝突待處理','out-of-scope':'不在範圍'};
const stateLabels={open:'未回收',delayed:'延後',fulfilled:'實現',subverted:'推翻'};
const ownValue = <T,>(map: Record<string,T> | undefined, key: string): T | undefined => map && Object.prototype.hasOwnProperty.call(map,key) ? map[key] : undefined;
const colors=['#65d9ff','#b9a1ff','#ffbd80','#83dfb3','#fc91af','#99baff'];
function TextEntry({value,onSave,label}:{value:string;onSave:(v:string)=>void;label:string}){
  const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);
  return <input aria-label={label} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==value)onSave(draft);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>;
}
export default function AudienceRuleEngine({onBack,onAtlas}:{onBack:()=>void;onAtlas:()=>void}){
  const p=useEditor(s=>s.project),selected=useEditor(s=>s.occurrenceId),config=engineConfig(p),list=p.timelines.audience.placements;
  const item=list.find(o=>o.id===selected)??list[0],index=list.indexOf(item),unit=p.units.find(u=>u.id===item.eventId)!;
  const [newKind,setNewKind]=useState('expectation.establish'),[move,setMove]=useState<DirectorMove>('plant'),[showSeed,setShowSeed]=useState(false),[seedKey,setSeedKey]=useState('clue-known');
  const currentInput=useMemo(()=>engineInput(p),[p]);
  const run=useMemo(()=>replaySimulation(p.audienceEngine?.lastRun),[p.audienceEngine?.lastRun]);
  const baseline=useMemo(()=>replaySimulation(p.audienceEngine?.baseline),[p.audienceEngine?.baseline]);
  const stale=!!run&&isRunStale(run,currentInput),point=run?.checkpoints.find(c=>c.occurrenceId===item.id),trace=run?.trace.filter(t=>t.occurrenceId===item.id||t.occurrenceId===null)??[];
  const tx=(fn:Parameters<typeof configureEngine>[1])=>editor.getState().transact(q=>configureEngine(q,fn));
  const update=(id:string,patch:Partial<RuleInstance>)=>tx(c=>{const r=c.rules.find(r=>r.id===id);if(r)Object.assign(r,patch);});
  const add=(director=false)=>tx(c=>{const r=newRule(uid(),item.id,director?directorMoves[move].ruleId:newKind);r.order=(c.rules.filter(x=>x.occurrenceId===item.id).at(-1)?.order??0)+10;r.target=[...c.rules].reverse().find(x=>x.ruleId.startsWith('expectation.'))?.target??'expectation-1';if(director)r.source={kind:'director',move,eventId:item.eventId,revision:unit.stages.director.revision};c.rules.push(r);});
  const select=(id:string)=>{const o=list.find(o=>o.id===id)!;editor.setState({basis:'audience',occurrenceId:id,selectedId:o.eventId,playhead:list.indexOf(o)+.5});};
  const keys=run&&!stale?[...new Set(run.checkpoints.flatMap(c=>Object.keys(c.after.expectations)))]:[];
  const w=Math.max(720,list.length*100),x=(i:number)=>45+(i*(w-85))/Math.max(1,list.length-1),y=(v:number)=>175-v*130;
  const compare=baseline&&run?compareRuns(baseline,run):null;
  const rules=config.rules.filter(r=>r.occurrenceId===item.id).sort((a,b)=>a.order-b.order||(a.id<b.id?-1:1));
  const addCondition=(r:RuleInstance)=>update(r.id,{conditions:[...r.conditions,{kind:'knowledge',key:'clue-known',equals:true}]});
  const conditionChange=(r:RuleInstance,i:number,c:Condition)=>update(r.id,{conditions:r.conditions.map((old,j)=>i===j?c:old)});
  const demo=()=>tx(c=>{const target='demo-'+Date.now();['establish','reinforce','delay','fulfill','subvert'].forEach((kind,i)=>{if(!list[i])return;const r=newRule(uid(),list[i].id,'expectation.'+kind);r.target=kind==='subvert'?target+'-alternative':target;r.text=kind==='subvert'?'另一條預測：有人會阻止揭曉':'門後有人等待';r.amount=kind==='reinforce'?.2:.4;c.rules.push(r);if(kind==='subvert'){const setup=newRule(uid(),list[0].id);setup.target=r.target;setup.text=r.text;c.rules.push(setup);}});});
  return <section className="audience-engine" aria-label="Audience rule engine">
    <header className="engine-heading"><div><strong>觀眾狀態 · 規則模擬</strong><small>作者假設的確定性模型 · 不預測真實觀眾的心理</small></div><div><button onClick={onBack}>作者設計</button><button onClick={onAtlas}>回到空間圖</button></div></header>
    <div className="engine-flow"><span>作者目標</span><b>→</b><span>明確規則＋權重</span><b>→</b><span className="engine-active">模擬狀態</span><i>實測回饋另存，不由模型推斷</i></div>
    <div className="engine-toolbar"><button className="primary" onClick={()=>editor.getState().transact(runSimulation)}>▶ 重新運算</button><button disabled={!run||stale} onClick={()=>editor.getState().transact(saveSimulationBaseline)}>保存為比較基準</button><button aria-expanded={showSeed} onClick={()=>setShowSeed(!showSeed)}>初始狀態／衰減</button>{!config.rules.length&&<button onClick={demo}>加入五種示範規則</button>}<span role="status">{stale?'設定已變更 · 結果待重算':run?run.complete?'計算完成':'結果不完整 · 有未解輸入':'尚未運算'}</span></div>
    {p.audienceEngine?.lastRun&&!run&&<p className="engine-warning">儲存的模型版本不同，請重新運算；舊基準仍保留</p>}
    <div className="engine-caption">強度 0–1；權重 0–2 是可調的作者假設，未經實證校準。橫軸是 Audience 出現順序，沒有把它當成秒數</div>
    {showSeed&&<div className="engine-seed"><h3>進入故事前的狀態</h3><div className="engine-inline"><input aria-label="Initial state key" value={seedKey} onChange={e=>setSeedKey(e.target.value)} placeholder="key-in-english"/><button onClick={()=>tx(c=>{c.initial.knowledge[seedKey]=true;})}>加入已知資訊</button><button onClick={()=>tx(c=>{c.initial.beliefs[seedKey]=.5;})}>加入相信程度</button></div><small>key 使用英文字母、數字、- 或 _；未設定與 unknown 都不等於 0</small>
      {Object.entries(config.initial.knowledge).map(([key,value])=><div className="engine-inline" key={'k'+key}><span>知道 · {key}</span><select aria-label={'Knowledge '+key} value={value===null?'unknown':String(value)} onChange={e=>tx(c=>{c.initial.knowledge[key]=e.target.value==='unknown'?null:e.target.value==='true';})}><option value="true">已知</option><option value="false">明確未知</option><option value="unknown">未指定</option></select><button onClick={()=>tx(c=>{delete c.initial.knowledge[key];})}>移除</button></div>)}
      {Object.entries(config.initial.beliefs).map(([key,value])=><div className="engine-inline" key={'b'+key}><span>相信 · {key}</span><input aria-label={'Belief '+key} type="number" min="0" max="1" step=".05" value={value??''} placeholder="unknown" onChange={e=>tx(c=>{c.initial.beliefs[key]=e.target.value===''?null:Number(e.target.value);})}/><button onClick={()=>tx(c=>{delete c.initial.beliefs[key];})}>移除</button></div>)}
      <label className="engine-inline"><input type="checkbox" checked={config.decay.enabled} onChange={e=>tx(c=>{c.decay.enabled=e.target.checked;})}/>每經過一個出現間隔，衰減未回收預期<input aria-label="Decay per occurrence" type="number" min="0" max="1" step=".01" value={config.decay.perStep} onChange={e=>tx(c=>{c.decay.perStep=Number(e.target.value);})}/></label><small>先衰減，再按規則順序執行；實現／推翻後停止衰減</small>
    </div>}
    <div className="engine-chart-scroll" tabIndex={0} aria-label="Simulated expectation strengths"><svg viewBox={`0 0 ${w} 220`} style={{width:w,minWidth:'100%'}} role="img" aria-label="Expectation strength by audience occurrence, simulated not measured">{[0,.5,1].map(v=><g key={v}><line x1="35" x2={w-20} y1={y(v)} y2={y(v)} stroke="#2b4050"/><text x="5" y={y(v)+5} fill="#9fadb9" fontSize="12">{v}</text></g>)}{keys.slice(0,6).map((key,k)=><g key={key} stroke={colors[k]}>{run!.checkpoints.map((c,i)=>{const e=ownValue(c.after.expectations,key),prev=ownValue(run!.checkpoints[i-1]?.after.expectations,key);return e?<g key={c.occurrenceId}>{prev&&<line x1={x(i-1)} x2={x(i)} y1={y(prev.strength)} y2={y(e.strength)} strokeWidth="2" opacity={stale?.45:.85}/>}<circle cx={x(i)} cy={y(e.strength)} r={c.occurrenceId===item.id?6:4} fill={e.status==='open'||e.status==='delayed'?colors[k]:'#101c29'}><title>{key}: {e.strength.toFixed(3)} · {stateLabels[e.status]}{!c.complete?' · 不完整':''}</title></circle></g>:null;})}</g>)}{!keys.length&&<text x="50" y="100" fill="#9fadb9" fontSize="15">{stale?'設定或順序已變更，重算後再顯示曲線':'新增規則並運算，查看每次呈現如何改變預期'}</text>}{list.map((o,i)=><g key={o.id} onClick={()=>select(o.id)}><text x={x(i)} y="207" textAnchor="middle" fill={o.id===item.id?'#ffffff':'#91a8bb'} fontSize="12">{i+1}</text></g>)}</svg></div>
    <div className="engine-legend">{keys.slice(0,6).map((key,i)=><span key={key} style={{color:colors[i]}}>● {ownValue(run?.final.expectations,key)?.text||key}</span>)}{keys.length>6&&<span>圖表顯示前 6 條；所有結果在下方</span>}</div>
    <nav className="engine-occurrences" aria-label="Audience simulation occurrences">{list.map((o,i)=><button key={o.id} aria-pressed={o.id===item.id} onClick={()=>select(o.id)}><span>{String(i+1).padStart(2,'0')}</span><b>{p.units.find(u=>u.id===o.eventId)?.title}</b><small>{config.rules.filter(r=>r.occurrenceId===o.id).length} 條規則</small></button>)}</nav>
    {run&&!run.complete&&<p className="engine-warning" role="alert">有 {run.unresolvedCount} 項未知、未註冊或衝突；顯示的是已知規則的部分結果，未解效果不計成零。請展開「整體執行紀錄」檢查</p>}
    <div className="engine-selection"><h2>{index+1} · {unit.title}</h2><small>canonical event: {item.eventId} · Audience occurrence: {item.id}</small></div>
    <div className="engine-comparison"><div><small>作者目標 · 不自動轉成規則</small><p>{item.audienceDesign?.cognition.believes||unit.audienceEffect||'尚未填寫'}</p></div><div><small>模擬輸出 {stale?'· 待重算':''}</small><p>{point?`${Object.keys(point.after.expectations).length} 個預期 · ${trace.filter(t=>t.status==='applied').length} 條已套用`:'尚未運算'}</p></div><div><small>實測回饋 · 獨立來源</small><p>{item.audienceObservations?.length?`${item.audienceObservations.length} 筆已記錄回饋`:'尚未輸入觀眾回饋'}</p></div></div>
    {point&&<div className="engine-result-list">{Object.entries(point.after.expectations).map(([key,e])=>{const prev=ownValue(point.before.expectations,key);return <div className="engine-state-card" key={key}><b>{e.text}</b><small>{key}</small><div className="engine-strength"><i style={{width:`${e.strength*100}%`}}/></div><span>{prev?prev.strength.toFixed(2):'未建立'} → {e.strength.toFixed(2)} · {stateLabels[e.status]}</span></div>;})}</div>}
    <div className="engine-rule-heading"><h3>這次呈現的規則</h3><select aria-label="New rule type" value={newKind} onChange={e=>setNewKind(e.target.value)}>{Object.values(ruleRegistry).map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select><button onClick={()=>add()}>＋ 加入規則</button></div>
    <div className="engine-inline engine-director"><span>導演手法映射</span><select aria-label="Director move" value={move} onChange={e=>setMove(e.target.value as DirectorMove)}>{Object.entries(directorMoves).map(([key,value])=><option value={key} key={key}>{value.label}</option>)}</select><span>→ {ruleRegistry[directorMoves[move].ruleId].label}</span><button onClick={()=>add(true)}>加入映射</button><small>明確選取才套用；導演稿變更後需重新確認</small></div>
    {!rules.length&&<p className="engine-empty">此處尚未設定規則。建立預期後，在後續出現使用相同的 target key 來強化、延後、實現或推翻</p>}
    {rules.map(r=><details className="engine-rule" key={r.id}><summary><span className={'engine-rule-dot '+(!r.enabled?'off':'')}/><b>{Object.prototype.hasOwnProperty.call(ruleRegistry,r.ruleId)?ruleRegistry[r.ruleId].label:r.ruleId}</b><span>{r.target}</span><small>×{r.weight} · 順序 {r.order}</small></summary><div className="engine-rule-fields"><label>目標 key<TextEntry value={r.target} onSave={v=>update(r.id,{target:v})} label={'Target '+r.id}/></label><label>顯示文字<TextEntry value={r.text} onSave={v=>update(r.id,{text:v})} label={'Rule text '+r.id}/></label><label>增量／初始強度<input type="number" aria-label={'Amount '+r.id} step=".05" min={r.ruleId==='belief.adjust'?-1:0} max="1" value={r.amount} disabled={['expectation.delay','expectation.fulfill','expectation.subvert','knowledge.reveal'].includes(r.ruleId)} onChange={e=>update(r.id,{amount:Number(e.target.value)})}/></label><label>權重<input type="number" aria-label={'Weight '+r.id} min="0" max="2" step=".1" value={r.weight} onChange={e=>update(r.id,{weight:Number(e.target.value)})}/></label><label>執行順序<input type="number" aria-label={'Order '+r.id} min="0" max="9999" value={r.order} onChange={e=>update(r.id,{order:Number(e.target.value)})}/></label><label>預期類型<select value={r.expectationKind} onChange={e=>update(r.id,{expectationKind:e.target.value as RuleInstance['expectationKind']})}><option value="prediction">預測</option><option value="hope">希望</option><option value="fear">擔心</option></select></label><label>飽和方式<select value={r.saturation} onChange={e=>update(r.id,{saturation:e.target.value as RuleInstance['saturation']})}><option value="linear">線性＋0–1 截限</option><option value="headroom">依剩餘空間縮小增量</option></select></label><label>同目標衝突<select value={r.conflict} onChange={e=>update(r.id,{conflict:e.target.value as RuleInstance['conflict']})}><option value="ordered">按順序累積</option><option value="exclusive">排他：已有寫入則阻擋</option></select></label></div><small>分類動作不按權重縮放；權重 0 停用，正值執行。強度與相信程度明確截在 0–1</small>
      <div className="engine-inline"><label><input type="checkbox" checked={r.enabled} onChange={e=>update(r.id,{enabled:e.target.checked})}/> 啟用</label><label><input type="checkbox" checked={!!r.range} onChange={e=>update(r.id,{range:e.target.checked?{startId:list[0].id,endId:list.at(-1)!.id}:undefined})}/>限制範圍</label>{r.range&&<><select aria-label={'Range start '+r.id} value={r.range.startId} onChange={e=>update(r.id,{range:{...r.range!,startId:e.target.value}})}>{list.map((o,i)=><option value={o.id} key={o.id}>{i+1} · {o.eventId}</option>)}</select><span>→</span><select aria-label={'Range end '+r.id} value={r.range.endId} onChange={e=>update(r.id,{range:{...r.range!,endId:e.target.value}})}>{list.map((o,i)=><option value={o.id} key={o.id}>{i+1} · {o.eventId}</option>)}</select></>}</div>
      <div className="engine-conditions"><b>全部條件成立才執行</b>{r.conditions.map((c,i)=><div className="engine-inline" key={i}><select aria-label={'Condition kind '+r.id+' '+i} value={c.kind} onChange={e=>conditionChange(r,i,e.target.value==='knowledge'?{kind:'knowledge',key:c.key,equals:true}:e.target.value==='belief'?{kind:'belief',key:c.key,op:'gte',value:.5}:{kind:'expectation',key:c.key,status:'active'})}><option value="knowledge">已知資訊</option><option value="belief">相信程度</option><option value="expectation">預期狀態</option></select><TextEntry value={c.key} label={'Condition key '+r.id+' '+i} onSave={v=>conditionChange(r,i,{...c,key:v})}/>{c.kind==='knowledge'?<select value={String(c.equals)} onChange={e=>conditionChange(r,i,{...c,equals:e.target.value==='true'})}><option value="true">已知</option><option value="false">明確未知</option></select>:c.kind==='belief'?<><select value={c.op} onChange={e=>conditionChange(r,i,{...c,op:e.target.value as 'gte'|'lte'})}><option value="gte">≥</option><option value="lte">≤</option></select><input type="number" min="0" max="1" step=".05" value={c.value} onChange={e=>conditionChange(r,i,{...c,value:Number(e.target.value)})}/></>:<select value={c.status} onChange={e=>conditionChange(r,i,{...c,status:e.target.value as typeof c.status})}>{['active','absent','open','delayed','fulfilled','subverted'].map(s=><option key={s}>{s}</option>)}</select>}<button onClick={()=>update(r.id,{conditions:r.conditions.filter((_,j)=>i!==j)})}>移除條件</button></div>)}<button onClick={()=>addCondition(r)}>＋ 加入條件</button></div>
      <div className="engine-inline"><small>來源：{r.source.kind==='manual'?'手動規則':r.source.kind==='director'?`導演手法 · ${directorMoves[r.source.move].label} · revision ${r.source.revision}`:'使用者已接受的提案'}</small>{r.source.kind==='director'&&<button onClick={()=>update(r.id,{source:{...r.source as Extract<RuleInstance['source'],{kind:'director'}>,eventId:item.eventId,revision:unit.stages.director.revision}})}>確認目前導演版本</button>}<button onClick={()=>tx(c=>{c.rules=c.rules.filter(x=>x.id!==r.id);})}>刪除規則</button></div>
    </details>)}
    {!!config.rules.filter(r=>!list.some(o=>o.id===r.occurrenceId)).length&&<details className="engine-rule"><summary>已失去出現連結的規則 · 待修復</summary>{config.rules.filter(r=>!list.some(o=>o.id===r.occurrenceId)).map(r=><div className="engine-inline" key={r.id}><span>{r.target} · {r.ruleId}</span><button onClick={()=>update(r.id,{occurrenceId:item.id})}>連到目前出現</button><button onClick={()=>tx(c=>{c.rules=c.rules.filter(x=>x.id!==r.id);})}>刪除</button></div>)}</details>}
    <details className="engine-traces"><summary>本次呈現 · 前後狀態與因果紀錄（{trace.length}）</summary>{point&&<div className="engine-state-json"><div><b>Before</b><pre>{JSON.stringify(point.before,null,2)}</pre></div><div><b>After</b><pre>{JSON.stringify(point.after,null,2)}</pre></div></div>}{trace.map(t=><details key={t.id} className={'engine-trace '+t.status}><summary><b>{statusLabel[t.status]}</b> · {t.ruleId} · {t.rule?.target??'全部未回收預期'}</summary><p>{t.reason}</p><small>規則 {t.instanceId} · 出現 {t.occurrenceId??'已移除'} · 事件 {t.eventId??'未知'}</small>{t.deltas.map((d,i)=><p key={i}>{d.path}: {JSON.stringify(d.before)} → {JSON.stringify(d.after)}{d.clamped?' · 已截限':''}{d.requested!==undefined?` · requested ${d.requested.toFixed(3)} / effective ${(d.effective??0).toFixed(3)}`:''}</p>)}<pre>{JSON.stringify({input:t.reads,rule:t.rule},null,2)}</pre></details>)}</details>
    {run&&<details className="engine-traces"><summary>整體執行紀錄 · {run.trace.length} 筆 · {run.unresolvedCount} 待解</summary>{run.trace.map(t=><div className="engine-trace-row" key={t.id}><button disabled={!t.occurrenceId||!list.some(o=>o.id===t.occurrenceId)} onClick={()=>select(t.occurrenceId!)}>{t.ordinal??'?'} · {t.rule?.target??'decay'}</button><span className={t.status}>{statusLabel[t.status]}</span><small>{t.reason}</small></div>)}<details><summary>可重現輸入快照 · {run.engineVersion}</summary><pre>{JSON.stringify(run.input,null,2)}</pre></details></details>}
    {compare&&<details className="engine-traces"><summary>與基準比較 {stale?'· 目前結果尚待重算':''}</summary>{!compare.comparable&&<p className="engine-warning">至少一次運算不完整；不計算數值差異，避免把未知當成零</p>}{compare.rows.map(row=><p key={row.key}>{row.after?.text||row.before?.text||row.key}: {row.before?.strength.toFixed(2)??'未建立'} → {row.after?.strength.toFixed(2)??'未建立'} · Δ {row.strengthDelta===null?'不可比較':row.strengthDelta.toFixed(3)} · {row.before?.status??'unknown'} → {row.after?.status??'unknown'}</p>)}</details>}
    <footer className="engine-footer">本地執行，不呼叫外部模型。未來模型只可提出規則草案；使用者接受後才加入。設定、運算輸入與基準隨專案儲存，可匯出與復原</footer>
  </section>;
}
