import { useEffect, useMemo, useState, type FormEvent, type CSSProperties } from 'react';
import { AtlasIcon, basisNames } from './AtlasIcon';
import { editor, useEditor } from './store';
import { clone, uid, type Project } from './model';
import { bases, type TimeBasis } from './temporal';
import type { TimelineCursor } from './playback';
import { anchorKey, contentAnchor, contentNumberSegments, contentSeries, dimensionLabels, epistemicLabels, targetLabel, newContentTrack, ownerKey, ownerLabel, removeContentEntry, removeContentTrack, saveContentTrack, setContentEntry, sourceLabel, trackDimensions, visibleContentTracks, type ContentEntry, type ContentOwner, type ContentSource, type ContentTrack, type TrackDimension, type Epistemic } from './storyTracks';
import { emotionTypes } from './audience';
import { emotionLabels } from './AuthoredEmotionChart';

export function openContentTrack(id?: string, cursor?: TimelineCursor) {
  const p = editor.getState().project, item = cursor && p.timelines[cursor.basis].placements.find(o => o.id === cursor.occurrenceId);
  editor.setState({ panel: 'tracking', inspectorOpen: true, outlineOpen: false, ...(id ? { contentTrackId: id } : {}), ...(cursor && item ? { ...cursor, selectedId: item.eventId, playhead: p.timelines[cursor.basis].placements.indexOf(item) + .5 } : {}) });
}
export function StoryTrackControls() {
  const { project: p, trackingOwner, trackingDimension, hiddenContentTrackIds } = useEditor(s => s), tracks = p.storyTracks ?? [];
  const owners = [...new Map(tracks.map(t => [ownerKey(t.owner), ownerLabel(p, t.owner)])).entries()];
  return <div className="content-track-controls" aria-label="內容追蹤顯示選擇">
    <span><AtlasIcon name="layers"/>追蹤內容</span>
    {!!tracks.length && <><label>對象<select aria-label="Tracking owner filter" value={owners.some(([key]) => key === trackingOwner) ? trackingOwner : 'all'} onChange={e => editor.setState({ trackingOwner: e.target.value })}><option value="all">所有對象</option>{owners.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>維度<select aria-label="Tracking dimension filter" value={tracks.some(t => t.dimension === trackingDimension) ? trackingDimension : 'all'} onChange={e => editor.setState({ trackingDimension: e.target.value })}><option value="all">所有維度</option>{trackDimensions.filter(d => tracks.some(t => t.dimension === d)).map(d => <option key={d} value={d}>{dimensionLabels[d]}</option>)}</select></label><details className="track-visibility"><summary>顯示 {tracks.length - tracks.filter(t => hiddenContentTrackIds.includes(t.id)).length}/{tracks.length}</summary><div>{tracks.map(t => <label key={t.id}><input type="checkbox" aria-label={`Show content track ${t.name}`} checked={!hiddenContentTrackIds.includes(t.id)} onChange={e => editor.setState({ hiddenContentTrackIds: e.target.checked ? hiddenContentTrackIds.filter(id => id !== t.id) : [...hiddenContentTrackIds, t.id] })}/>{ownerLabel(p, t.owner)} · {t.name}</label>)}</div></details></>}
    <button onClick={() => openContentTrack()} aria-label="Manage content tracks"><AtlasIcon name="edit"/>{tracks.length ? '編輯追蹤' : '新增追蹤'}</button>
  </div>;
}
function TrackRow({ p, track, occurrenceId, onSelect }: { p: Project; track: ContentTrack; occurrenceId?: string; onSelect?: (cursor: TimelineCursor, element?: HTMLElement) => void }) {
  const series = useMemo(() => contentSeries(p, track), [p, track]);
  const at = series.find(s => s.occurrenceId === occurrenceId), number = track.representation === 'number';
  const x = (i: number) => (i + .5) * 600 / Math.max(1, series.length), y = (value: number) => 62 - (value - track.scale!.min) / (track.scale!.max - track.scale!.min) * 48;
  const select = (id: string, element: HTMLElement) => { const cursor = { basis: track.basis, occurrenceId: id }; onSelect?.(cursor, element); openContentTrack(track.id, cursor); };
  return <div className="content-track-row" data-content-track={track.id} data-dimension={track.dimension}>
    <button className="content-row-label" onClick={() => openContentTrack(track.id)} title={track.meaning || '編輯名称、含義與資料'}><b>{track.name}</b><small>{dimensionLabels[track.dimension]}{track.targetTrackId ? ' · 關於 ' + targetLabel(p, track) : ''} · {track.source.kind === 'manual' ? '自訂' : '已有設定'}</small></button>
    <div className="content-row-data"><div className="content-lane-scroll" style={{ "--content-lane-touch-width": `${Math.max(1, series.length) * 44}px` } as CSSProperties}>
      {number ? <div className="content-number-lane"><svg viewBox="0 0 600 78" preserveAspectRatio="none" role="img" aria-label={`${track.name}，${track.scale!.minLabel} ${track.scale!.min} 至 ${track.scale!.maxLabel} ${track.scale!.max}；空白保留斷線`}><line x1="0" x2="600" y1="62" y2="62" stroke="currentColor" vectorEffect="non-scaling-stroke" opacity=".2"/>{contentNumberSegments(series, p, track).map(({ from, to }) => <line key={to.occurrenceId} data-content-segment={track.id} x1={x(from.index)} x2={x(to.index)} y1={y(from.value as number)} y2={y(to.value as number)} stroke="currentColor" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>)}{series.filter(s => typeof s.value === 'number').map(s => <line key={s.occurrenceId} data-content-point={s.occurrenceId} x1={x(s.index)} x2={x(s.index)} y1={y(s.value as number)} y2={y(s.value as number)} stroke="currentColor" strokeWidth={s.occurrenceId === occurrenceId ? 8 : 5} strokeLinecap="round" vectorEffect="non-scaling-stroke"><title>{s.index + 1} · {s.value}</title></line>)}</svg><div className="content-number-targets" style={{ gridTemplateColumns: `repeat(${series.length}, minmax(0, 1fr))` }}>{series.map(s => <button key={s.occurrenceId} aria-label={`${track.name} 第 ${s.index + 1} 節點：${s.value ?? '未知'}`} title={`${s.index + 1} · ${p.units.find(u => u.id === s.eventId)?.title} · ${s.value ?? '未填'}`} data-current={s.occurrenceId === occurrenceId} onClick={e => select(s.occurrenceId, e.currentTarget)}/>)}</div></div> : <div className="content-state-lane" style={{ gridTemplateColumns: `repeat(${series.length}, minmax(0, 1fr))` }}>{series.map(s => <button key={s.occurrenceId} data-current={s.occurrenceId === occurrenceId} data-unknown={s.value === null} data-explicit={s.explicit} aria-label={`${track.name} 第 ${s.index + 1} 節點：${s.value ?? '未知'}`} title={`${s.index + 1} · ${p.units.find(u => u.id === s.eventId)?.title}\n${s.value ?? '未知'}${s.reveal ? ' → ' + (p.units.find(u => u.id === s.reveal!.eventId)?.title ?? '') : ''}\n${s.provenance}`} onClick={e => select(s.occurrenceId, e.currentTarget)}><span>{s.explicit ? s.value === null ? '?' : track.representation === 'link' ? '◇' : '●' : s.value === null ? '·' : '─'}</span>{s.explicit && <small>{String(s.value ?? '未知')}</small>}</button>)}</div>}
      </div><div className="content-current-value"><strong>{at ? String(at.value ?? '未知') : '請選擇這條順序的確切節點'}</strong>{at?.reveal && <span>→ {p.units.find(u => u.id === at.reveal!.eventId)?.title}</span>}<small>{track.epistemic ? epistemicLabels[track.epistemic] + ' · ' : ''}{at?.provenance ?? sourceLabel(track)}{at?.inherited ? ' · 沿用已寫狀態' : ''}{number ? ` · ${track.scale!.min}–${track.scale!.max}` : ''}</small></div>
    </div>
  </div>;
}
export function StoryTrackRows({ p, basis, occurrenceId, onSelect }: { p: Project; basis: TimeBasis; occurrenceId?: string; onSelect?: (cursor: TimelineCursor, element?: HTMLElement) => void }) {
  const { trackingOwner, trackingDimension, hiddenContentTrackIds } = useEditor(s => s);
  const tracks = visibleContentTracks(p, { owner: trackingOwner, dimension: trackingDimension, hiddenIds: hiddenContentTrackIds }, basis);
  const groups = [...new Set(tracks.map(t => ownerKey(t.owner)))];
  if (!tracks.length) return null;
  return <div className="content-track-groups" aria-label={`${basisNames[basis]}的內容追蹤`}>{groups.map(key => <section key={key} data-content-owner={key}><h4><AtlasIcon name={key === 'audience' ? 'audience' : 'person'}/>{ownerLabel(p, tracks.find(t => ownerKey(t.owner) === key)!.owner)}</h4>{tracks.filter(t => ownerKey(t.owner) === key).map(t => <TrackRow p={p} key={t.id} track={t} occurrenceId={occurrenceId} onSelect={onSelect}/>)}</section>)}</div>;
}

function TrackDefinition({ track, creating, onDone }: { track: ContentTrack; creating: boolean; onDone: (id?: string) => void }) {
  const p = useEditor(s => s.project), chars = p.tracks.filter(t => t.kind === 'character');
  const [draft, setDraft] = useState(() => clone(track));
  useEffect(() => setDraft(clone(track)), [p, track]);
  const patch = (values: Partial<ContentTrack>) => setDraft(d => ({ ...d, ...values }));
  const owner = draft.owner, locked = !!draft.entries.length;
  function chooseOwner(kind: ContentOwner['kind']) { patch({ owner: kind === 'character' ? { kind, trackId: chars[0]?.id ?? '' } : kind === 'relationship' ? { kind, trackIds: [chars[0]?.id ?? '', chars[1]?.id ?? ''] } : kind === 'custom' ? { kind, label: '故事' } : { kind }, source: { kind: 'manual' }, targetTrackId: undefined, epistemic: undefined }); }
  function chooseSource(value: string) {
    const [kind, field] = value.split(':');
    if (kind === 'manual') patch({ source: { kind: 'manual' } });
    else if (kind === 'audience-emotion') patch({ source: { kind, emotion: field as any }, representation: 'number', scale: { min: 0, max: 100, minLabel: '低', maxLabel: '高' }, meaning: draft.meaning || '作者設定的相對強度；不是規則推導或實測觀眾反應', dimension: 'emotion' });
    else patch({ source: { kind, field } as ContentSource, representation: 'state', scale: undefined });
  }
  function submit(e: FormEvent) { e.preventDefault(); editor.getState().transact(next => saveContentTrack(next, draft)); if (!editor.getState().notice) { editor.setState({ contentTrackId: draft.id }); onDone(draft.id); } }
  const sourceValue = draft.source.kind + (draft.source.kind === 'snapshot' || draft.source.kind === 'audience-cognition' ? ':' + draft.source.field : draft.source.kind === 'audience-emotion' ? ':' + draft.source.emotion : '');
  return <form className="content-definition" onSubmit={submit} aria-label="Content track definition">
    {creating && <label>可選起點<select aria-label="Content track template" value={draft.dimension} onChange={e => { const dimension = e.target.value as TrackDimension, fresh = newContentTrack(draft.basis, dimension); setDraft({ ...fresh, id: draft.id, owner: draft.owner }); }}><option value="custom">空白自訂</option>{trackDimensions.filter(d => d !== 'custom').map(d => <option key={d} value={d}>{dimensionLabels[d]}（可改名）</option>)}</select></label>}
    <label>名稱<input aria-label="Content track name" value={draft.name} maxLength={300} required onChange={e => patch({ name: e.target.value })}/></label>
    <div className="content-form-pair"><label>所屬對象<select aria-label="Content owner type" value={owner.kind} disabled={locked && draft.source.kind !== 'manual'} onChange={e => chooseOwner(e.target.value as ContentOwner['kind'])}><option value="custom">自訂對象</option><option value="character" disabled={!chars.length}>人物</option><option value="relationship" disabled={chars.length < 2}>人物關係</option><option value="audience">觀眾</option></select></label><label>維度<select aria-label="Content track dimension" value={draft.dimension} onChange={e => patch({ dimension: e.target.value as TrackDimension })}>{trackDimensions.map(d => <option key={d} value={d}>{dimensionLabels[d]}</option>)}</select></label></div>
    {owner.kind === 'custom' && <label>對象名稱<input aria-label="Custom owner name" maxLength={300} required value={owner.label} onChange={e => patch({ owner: { kind: 'custom', label: e.target.value } })}/></label>}
    {owner.kind === 'character' && <label>人物<select aria-label="Content character" value={owner.trackId} onChange={e => patch({ owner: { kind: 'character', trackId: e.target.value } })}>{chars.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
    {owner.kind === 'relationship' && <div className="content-form-pair">{[0, 1].map(i => <label key={i}>人物 {i + 1}<select aria-label={`Relationship character ${i + 1}`} value={owner.trackIds[i]} onChange={e => { const ids = [...owner.trackIds] as [string, string]; ids[i] = e.target.value; patch({ owner: { kind: 'relationship', trackIds: ids } }); }}>{chars.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>)}</div>}
    {(owner.kind === 'character' || owner.kind === 'audience') && <div className="content-form-pair"><label>這是誰的認知／設定<select aria-label="Content epistemic status" value={draft.epistemic ?? ''} onChange={e => patch({ epistemic: e.target.value ? e.target.value as Epistemic : undefined })}><option value="">作者設定（未分類）</option>{(Object.keys(epistemicLabels) as Epistemic[]).filter(k => owner.kind === 'audience' ? k === 'audience-belief' || k === 'intended-response' : k === 'authored-fact' || k === 'self-belief').map(k => <option key={k} value={k}>{epistemicLabels[k]}</option>)}</select></label><label>關於哪個人物<select aria-label="Content target character" value={draft.targetTrackId ?? ''} onChange={e => patch({ targetTrackId: e.target.value || undefined })}><option value="">未指定對象</option>{chars.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>}
    <label>沿哪個順序追蹤<select aria-label="Content time basis" value={draft.basis} disabled={locked} onChange={e => patch({ basis: e.target.value as TimeBasis, source: { kind: 'manual' } })}>{bases.map(b => <option key={b} value={b}>{basisNames[b]}</option>)}</select></label>
    <label>資料來源<select aria-label="Content source" value={sourceValue} disabled={locked} onChange={e => chooseSource(e.target.value)}><option value="manual">直接填寫</option>{owner.kind === 'character' && <optgroup label={draft.basis === 'narrative' ? '沿用對應事件的世界快照（非觀眾已知）' : '沿用此順序中明確寫下的快照'}>{(['state', 'goal', 'knowledge', 'obstacle', 'motivation'] as const).map((field, i) => <option key={field} value={'snapshot:' + field}>{['狀態', '目標', '知道的事', '阻礙', '動機'][i]}</option>)}</optgroup>}{owner.kind === 'audience' && draft.basis === 'audience' && <><optgroup label="已有觀眾認知">{(['knows', 'believes', 'questions'] as const).map((field, i) => <option key={field} value={'audience-cognition:' + field}>{['知道', '相信', '追問'][i]}</option>)}</optgroup><optgroup label="已有作者情緒設定">{emotionTypes.map(k => <option key={k} value={'audience-emotion:' + k}>{emotionLabels[k]}</option>)}</optgroup></>}</select></label>
    <label>資料形式<select aria-label="Content representation" value={draft.representation} disabled={locked || draft.source.kind !== 'manual'} onChange={e => { const representation = e.target.value as ContentTrack['representation']; patch({ representation, scale: representation === 'number' ? { min: 0, max: 100, minLabel: '低', maxLabel: '高' } : undefined }); }}><option value="state">文字狀態／階段</option><option value="number">有定義的數值</option><option value="link">線索 → 回收節點</option></select></label>
    <label>{draft.representation === 'number' ? '數值代表什麼（必填）' : '這條線的含義'}<textarea aria-label="Content track meaning" rows={2} required={draft.representation === 'number'} maxLength={20000} value={draft.meaning} onChange={e => patch({ meaning: e.target.value })}/></label>
    {draft.representation === 'number' && draft.scale && <fieldset><legend>刻度定義</legend><div className="content-form-pair">{(['min', 'max'] as const).map((key, i) => <label key={key}>{i ? '上限' : '下限'}<input type="number" step="any" aria-label={`Content scale ${key}`} value={draft.scale![key]} disabled={draft.source.kind === 'audience-emotion'} onChange={e => patch({ scale: { ...draft.scale!, [key]: e.target.value === '' ? NaN : Number(e.target.value) } })}/><input aria-label={`Content scale ${key} label`} placeholder={i ? '上限含義' : '下限含義'} required maxLength={300} value={draft.scale![key === 'min' ? 'minLabel' : 'maxLabel']} onChange={e => patch({ scale: { ...draft.scale!, [key === 'min' ? 'minLabel' : 'maxLabel']: e.target.value } })}/></label>)}</div></fieldset>}
    <small>名稱與含義由你決定；資料附在既有順序上，不會建立新的時間軸。</small>
    <div className="content-form-actions"><button type="submit">{creating ? '建立追蹤' : '儲存定義'}</button><button type="button" onClick={() => onDone()}>取消</button></div>
  </form>;
}
function ContentPointEditor({ track }: { track: ContentTrack }) {
  const { project: p, basis, occurrenceId } = useEditor(s => s), list = p.timelines[track.basis].placements;
  const selected = basis === track.basis ? list.find(o => o.id === occurrenceId) : undefined;
  const [pointId, setPointId] = useState(selected?.id ?? list[0]?.id ?? '');
  useEffect(() => { if (selected) setPointId(selected.id); }, [selected?.id]);
  const item = list.find(o => o.id === pointId) ?? list[0], anchor = contentAnchor(track.basis, item);
  const entry = track.entries.find(e => anchorKey(e.anchor) === anchorKey(anchor));
  const current = contentSeries(p, track).find(s => s.occurrenceId === item.id)!;
  const [value, setValue] = useState(entry?.value === null || entry?.value === undefined ? '' : String(entry.value)), [unknown, setUnknown] = useState(entry?.value === null), [note, setNote] = useState(entry?.note ?? ''), [revealId, setRevealId] = useState(entry?.reveal ? anchorKey(entry.reveal) : '');
  useEffect(() => { setValue(entry?.value === null || entry?.value === undefined ? '' : String(entry.value)); setUnknown(entry?.value === null); setNote(entry?.note ?? ''); setRevealId(entry?.reveal ? anchorKey(entry.reveal) : ''); }, [p, item.id, JSON.stringify(entry)]);
  function submit(e: FormEvent) {
    e.preventDefault(); const target = list.find(o => (track.basis === 'reality' ? o.eventId : o.id) === revealId);
    const next: ContentEntry = { id: entry?.id ?? uid(), anchor, value: unknown ? null : track.representation === 'number' ? value.trim() ? Number(value) : null : value, note, ...(track.representation === 'link' ? { reveal: !unknown && target ? contentAnchor(track.basis, target) : null } : {}) };
    editor.getState().transact(nextProject => setContentEntry(nextProject, track.id, next));
  }
  const goSource = () => {
    if (track.source.kind === 'snapshot' && track.owner.kind === 'character' && !current.sourceAnchor && current.provenance.includes('開場')) { editor.setState({ panel: 'track', trackId: track.owner.trackId }); return; }
    const sourceBasis = track.source.kind === 'snapshot' && track.basis === 'narrative' ? 'reality' : track.basis;
    const sourceList = p.timelines[sourceBasis].placements;
    const sourceItem = current.sourceAnchor?.kind === 'occurrence' ? sourceList.find(o => o.id === (current.sourceAnchor as any).occurrenceId) : sourceList.find(o => o.eventId === (current.sourceAnchor?.eventId ?? item.eventId));
    if (!sourceItem) { editor.setState({ notice: '這個來源事件尚未排入世界列表，請先補上位置' }); return; }
    editor.setState({ focusRequest: { basis: sourceBasis, occurrenceId: sourceItem.id }, basis: sourceBasis, occurrenceId: sourceItem.id, selectedId: sourceItem.eventId, playhead: sourceList.indexOf(sourceItem) + .5, panel: sourceBasis === 'reality' ? 'edit' : 'compare', ...(track.owner.kind === 'character' ? { trackId: track.owner.trackId } : {}) });
  };
  return <section className="content-point-editor"><label>目前節點<select aria-label="Content point occurrence" value={item.id} onChange={e => { const next = list.find(o => o.id === e.target.value)!; setPointId(next.id); editor.setState({ basis: track.basis, occurrenceId: next.id, selectedId: next.eventId, playhead: list.indexOf(next) + .5 }); }}>{list.map((o, i) => <option key={o.id} value={o.id}>{i + 1} · {p.units.find(u => u.id === o.eventId)?.title}{o.mode === 'repeat' ? '（再次呈現）' : ''}</option>)}</select></label>
    <div className="content-point-current"><small>{basisNames[track.basis]} · {current.provenance}</small><b>{String(current.value ?? '未知')}</b>{current.reveal && <span>→ {p.units.find(u => u.id === current.reveal!.eventId)?.title}</span>}</div>
    {track.source.kind !== 'manual' ? <><p className="content-help">值來自已有作者設定。此處不另存一份，也不混入規則推導或觀眾觀察。</p><button onClick={goSource}>開啟來源設定</button></> : <form onSubmit={submit} aria-label="Content point editor"><label><input type="checkbox" aria-label="Content point unknown" checked={unknown} onChange={e => setUnknown(e.target.checked)}/>這個節點明確標為未知</label><label>{track.representation === 'number' ? '作者設定數值' : track.representation === 'link' ? '這個線索是什麼' : '變成什麼狀態／階段'}<input aria-label="Content point value" type={track.representation === 'number' ? 'number' : 'text'} step={track.representation === 'number' ? 'any' : undefined} min={track.scale?.min} max={track.scale?.max} required={!unknown} maxLength={20000} value={value} disabled={unknown} onChange={e => setValue(e.target.value)}/></label>
    {track.representation === 'link' && <label>明確回收於<select aria-label="Content reveal target" value={revealId} disabled={unknown} onChange={e => setRevealId(e.target.value)}><option value="">尚未指定回收</option>{list.filter(o => o.id !== item.id).map((o, i) => <option key={o.id} value={track.basis === 'reality' ? o.eventId : o.id}>{list.indexOf(o) + 1} · {p.units.find(u => u.id === o.eventId)?.title}{o.mode === 'repeat' ? '（再次呈現）' : ''}</option>)}</select></label>}
    <label>註記<textarea aria-label="Content point note" rows={2} maxLength={20000} value={note} onChange={e => setNote(e.target.value)}/></label><div className="content-form-actions"><button type="submit">{entry ? '儲存此更新' : '加入此節點更新'}</button>{entry && <button type="button" onClick={() => editor.getState().transact(next => removeContentEntry(next, track.id, entry.id))}>移除此更新</button>}</div><small>{track.representation === 'state' ? '沒有更新的節點沿用已寫狀態；明確未知會中止沿用。世界先後未定時不猜測。' : track.representation === 'number' ? '空白保留未知與斷線，不補零、不自動推估。' : '此連結只表示你指定的回收，不會推斷因果。'}</small></form>}
    {track.basis === 'reality' && track.entries.some(e => !list.some(o => o.eventId === e.anchor.eventId)) && <p className="content-help">有 {track.entries.filter(e => !list.some(o => o.eventId === e.anchor.eventId)).length} 筆保留在尚未安排世界位置的事件；重新加入該事件位置即可查看。</p>}
  </section>;
}
export default function StoryTracksPanel() {
  const { project: p, contentTrackId, basis } = useEditor(s => s), tracks = p.storyTracks ?? [], track = tracks.find(t => t.id === contentTrackId) ?? tracks[0];
  const [creating, setCreating] = useState(false), [editing, setEditing] = useState(false);
  useEffect(() => setEditing(false), [track?.id]);
  const fresh = useMemo(() => newContentTrack(basis), [creating]);
  return <div className="inspector-content content-tracks-panel"><header><h2><AtlasIcon name="layers"/>內容追蹤</h2><button aria-label="Create content track" disabled={tracks.length >= 48} onClick={() => { setCreating(true); setEditing(false); }}>＋ 追蹤</button></header>
    {creating ? <TrackDefinition key={fresh.id} track={fresh} creating onDone={() => setCreating(false)}/> : !track ? <><p>選擇對象與想觀察的維度，再沿世界、呈現或理解順序填寫。</p><button onClick={() => setCreating(true)}>建立第一條追蹤</button></> : <><label>目前追蹤<select aria-label="Selected content track" value={track.id} onChange={e => editor.setState({ contentTrackId: e.target.value })}>{tracks.map(t => <option key={t.id} value={t.id}>{ownerLabel(p, t.owner)} · {t.name}</option>)}</select></label><div className="content-track-identity"><h3>{track.name}</h3><small>{ownerLabel(p, track.owner)}{track.targetTrackId ? ' → ' + targetLabel(p, track) : ''} · {dimensionLabels[track.dimension]} · {basisNames[track.basis]}</small>{track.epistemic && <small>{epistemicLabels[track.epistemic]}</small>}{track.meaning && <p>{track.meaning}</p>}{track.example && <small>虛構故事的作者示例</small>}<button aria-expanded={editing} onClick={() => setEditing(!editing)}><AtlasIcon name="edit"/>名稱與定義 <AtlasIcon name="chevron"/></button></div>{editing && <TrackDefinition key={track.id + JSON.stringify(track)} track={track} creating={false} onDone={() => setEditing(false)}/>}<ContentPointEditor key={track.id} track={track}/><details className="content-track-management"><summary>追蹤管理</summary><button className="danger" onClick={() => { if (confirm(`刪除「${track.name}」及其追蹤值？故事事件與來源設定會保留，可復原。`)) editor.getState().transact(next => removeContentTrack(next, track.id)); }}>刪除此追蹤</button></details></>}
  </div>;
}
